### ISSUE TITLE
请求在release里加入arm64支持

### ISSUE THREAD

**Issue by jiayhuang** [kitUIN/bikabika#9]
这样就可以支持arm windows 设备啦

**Comment by kitUIN** [comment]
目前在重构
下个版本将一并支持arm

**Comment by kitUIN** [comment]
当前版本的ARM版本已经发布,请前往[release(Alpha 0.2.3)](https://github.com/kitUIN/bikabika/releases/tag/0.2.3) 查看
⚠️⚠️⚠️注意:Arm版本未经测试,可能存在预期之外的BUG(因为本人没有windows arm设备

**Comment by jiayhuang** [comment]
用 surface pro x测试了，体验很棒！

**Comment by kitUIN** [comment]
> 用 surface pro x测试了，体验很棒！

感谢支持
